package com.grupo3.sistemamarcacion.vistas;

import com.grupo3.sistemamarcacion.controladores.ValidarUsuario;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login2
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        userTxtField = new javax.swing.JTextField();
        passTxtField = new javax.swing.JPasswordField();
        ingresarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userLbl.setText("Usuario");
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        passLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passLbl.setText("Contraseña");
        getContentPane().add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        getContentPane().add(userTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 136, -1));
        getContentPane().add(passTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 136, -1));

        ingresarBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresarBtn.setText("Ingresar");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });
        
        getContentPane().add(ingresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 98, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grupo3/sistemamarcacion/vistas/fondo_login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -170, 470, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        String user = userTxtField.getText();
        String contrasenia = String.valueOf(passTxtField.getPassword());

        ValidarUsuario vu = new ValidarUsuario(user, contrasenia);

        if (vu.iniciar()) {
            this.rootPane.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    MenuPrincipal mp;
                    switch (vu.obtenerIdTipoEmpleado()) {
                        case 1:
                            mp = new MenuPrincipalAsesor(vu.obtenerIdEmpleado(),
                                    vu.obtenerIdTipoEmpleado());
                            mp.setVisible(true);
                            break;
                        case 2:
                            mp = new MenuPrincipalCoordinador(vu.obtenerIdEmpleado(),
                                    vu.obtenerIdTipoEmpleado());
                            mp.setVisible(true);
                            break;
                        case 3:
                            mp = new MenuPrincipalSupervisor(vu.obtenerIdEmpleado(),
                                    vu.obtenerIdTipoEmpleado());
                            mp.setVisible(true);
                            break;
                        case 4:
                            mp = new MenuPrincipalRRHH(vu.obtenerIdEmpleado(),
                                    vu.obtenerIdTipoEmpleado());
                            mp.setVisible(true);
                            break;
                        default:
                            System.out.println("El tipo de empleado no existe.");
                            break;
                    }
                }
            });

            dispose();
        } else {
            JOptionPane.showMessageDialog(this.rootPane,
                    "Verificar usuario y/o contraseña");
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField passTxtField;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userTxtField;
    // End of variables declaration//GEN-END:variables
}
