package com.grupo3.sistemamarcacion.vistas;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import com.grupo3.sistemamarcacion.controladores.InicioSesion;
import com.grupo3.sistemamarcacion.controladores.Marcar;
import com.grupo3.sistemamarcacion.empleado.Asesor;
import com.grupo3.sistemamarcacion.tipomarcacion.TipoMarcacion;

public class MenuPrincipalAsesor extends MenuPrincipal {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apeMatLbl;
    private javax.swing.JLabel apePatLbl;
    private javax.swing.JLabel areaLbl;
    private javax.swing.JLabel dniLbl;
    private javax.swing.JLabel forApeMat;
    private javax.swing.JLabel forApePat;
    private javax.swing.JLabel forAreaLbl;
    private javax.swing.JLabel forDniLbl;
    private javax.swing.JLabel forNombreLbl;
    private javax.swing.JLabel forTipoDocumento;
    private javax.swing.JButton marcarBtn;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel relojLbl;
    private javax.swing.JComboBox<String> tipMarcCmbBox;
    private javax.swing.JLabel tipoDocumento;
    // End of variables declaration//GEN-END:variables
    private Asesor asesor;
    public int idTipoMarcacion;

    public MenuPrincipalAsesor(String idEmpleado, int idTipoEmpleado)
    {
        super(idEmpleado, idTipoEmpleado);
        InicioSesion is = new InicioSesion(this.idEmpleado, this.idTipoEmpleado);
        this.asesor = (Asesor) is.obtenerEmpleado();
        this.initComponents();
        setLocationRelativeTo(null);
    }
    
    //Agrega tipos de marcaciones al combo box
    private void agregarTipoMarcacion() {
        for (TipoMarcacion tm : TipoMarcacion.values()) {
            tipMarcCmbBox.addItem(tm.obtenerNombre());
        }
    }

    //Obtener el id del tipo de marcación
    private int obtenerIdTipoMarcacion() {
        String nomTipoMarcacion = tipMarcCmbBox.getSelectedItem().toString();
        return TipoMarcacion.obtenerTipoMarcacion(nomTipoMarcacion).obtenerId();
    }

    //Realizar una marcación.
    public void marcar(String idEmp, LocalDateTime fecHorAct, int idTipMarc) {
        Marcar m = new Marcar(idEmp, fecHorAct, idTipMarc);
        if (m.ejecutar()) {
            JOptionPane.showMessageDialog(this.rootPane,
                    "Marcación realizada con exito");
        } else {
            System.out.println("Error al registrar marcación");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dniLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        apePatLbl = new javax.swing.JLabel();
        apeMatLbl = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JLabel();
        forDniLbl = new javax.swing.JLabel();
        forNombreLbl = new javax.swing.JLabel();
        forApePat = new javax.swing.JLabel();
        forApeMat = new javax.swing.JLabel();
        forTipoDocumento = new javax.swing.JLabel();
        marcarBtn = new javax.swing.JButton();
        relojLbl = new javax.swing.JLabel();
        areaLbl = new javax.swing.JLabel();
        forAreaLbl = new javax.swing.JLabel();
        tipMarcCmbBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal - Asesor");

        this.dniLbl.setText("ID:");
        this.forDniLbl.setText(this.asesor.obtenerUsuario());

        this.nombreLbl.setText("Nombre:");
        this.forNombreLbl.setText(this.asesor.obtenerNombre());

        this.apePatLbl.setText("Apellido Paterno:");
        this.forApePat.setText(this.asesor.obtenerApePat());

        this.apeMatLbl.setText("Apellido Materno:");
        this.forApeMat.setText(this.asesor.obtenerApeMat());

        this.tipoDocumento.setText("Tipo de documento:");
        //this.tipoDocumentoLbl.setText(this.asesor.obtenerTipoDocumento());

        marcarBtn.setText("Marcar");

        relojLbl.setText("Aqui va un reloj");

        this.areaLbl.setText("Area:");
        this.forAreaLbl.setText(this.asesor.obtenerArea());

        //Llenar ComboBox
        this.agregarTipoMarcacion();

        //Obtener el id del primer elemento del ComboBox al aparecer menu 
        //principal
        this.idTipoMarcacion = obtenerIdTipoMarcacion();
        
        //Evento marcar
        marcarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String idEmpleado = asesor.obtenerUsuario();
                LocalDateTime fechaHora = LocalDateTime.now();
                marcar(idEmpleado, fechaHora, idTipoMarcacion);
            }
        });

        //Cambiar el id de tipo de marcación cuando se elige otro elemento
        //del ComboBox
        tipMarcCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTipoMarcacion = obtenerIdTipoMarcacion();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaLbl)
                    .addComponent(marcarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apeMatLbl)
                    .addComponent(apePatLbl)
                    .addComponent(nombreLbl)
                    .addComponent(tipoDocumento)
                    .addComponent(dniLbl))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(relojLbl)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(forDniLbl)
                                    .addComponent(forApePat)
                                    .addComponent(forApeMat)
                                    .addComponent(forTipoDocumento)
                                    .addComponent(forAreaLbl))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(forNombreLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipMarcCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLbl)
                    .addComponent(forDniLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forNombreLbl)
                    .addComponent(nombreLbl)
                    .addComponent(tipMarcCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apePatLbl)
                    .addComponent(forApePat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apeMatLbl)
                    .addComponent(forApeMat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDocumento)
                    .addComponent(forTipoDocumento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaLbl)
                    .addComponent(forAreaLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relojLbl))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
