package com.grupo3.sistemamarcacion.vistas;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import com.grupo3.sistemamarcacion.controladores.InicioSesion;
import com.grupo3.sistemamarcacion.controladores.Marcar;
import com.grupo3.sistemamarcacion.empleado.Asesor;
import com.grupo3.sistemamarcacion.tipomarcacion.TipoMarcacion;

public class MenuPrincipalAsesor extends MenuPrincipal {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apeMatLbl;
    private javax.swing.JLabel apePatLbl;
    private javax.swing.JLabel areaLbl;
    private javax.swing.JLabel dniLbl;
    private javax.swing.JLabel forApeMat;
    private javax.swing.JLabel forApePat;
    private javax.swing.JLabel forAreaLbl;
    private javax.swing.JLabel forDniLbl;
    private javax.swing.JLabel forNombreLbl;
    private javax.swing.JLabel forTipoDocumento;
    private javax.swing.JButton marcarBtn;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JComboBox<String> tipMarcCmbBox;
    private javax.swing.JLabel tipoDocumento;
    // End of variables declaration//GEN-END:variables
    private Asesor asesor;
    private int idTipoMarcacion;

    public MenuPrincipalAsesor(String idEmpleado, int idTipoEmpleado)
    {
        super(idEmpleado, idTipoEmpleado);
        InicioSesion is = new InicioSesion(this.idEmpleado, this.idTipoEmpleado);
        this.asesor = (Asesor) is.obtenerEmpleado();
        this.initComponents();
        setLocationRelativeTo(null);
    }
    
    //Agrega tipos de marcaciones al combo box
    private void agregarTipoMarcacion() {
        for (TipoMarcacion tm : TipoMarcacion.values()) {
            tipMarcCmbBox.addItem(tm.obtenerNombre());
        }
    }

    //Obtener el id del tipo de marcación
    private int obtenerIdTipoMarcacion() {
        String nomTipoMarcacion = tipMarcCmbBox.getSelectedItem().toString();
        return TipoMarcacion.obtenerTipoMarcacion(nomTipoMarcacion).obtenerId();
    }

    //Realizar una marcación.
    private void marcar(String idEmp, LocalDateTime fecHorAct, int idTipMarc) {
        Marcar m = new Marcar(idEmp, fecHorAct, idTipMarc);
        if (m.ejecutar()) {
            JOptionPane.showMessageDialog(this.rootPane,
                    "Marcación realizada con exito");
        } else {
            System.out.println("Error al registrar marcación");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dniLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        apePatLbl = new javax.swing.JLabel();
        apeMatLbl = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JLabel();
        forDniLbl = new javax.swing.JLabel();
        forNombreLbl = new javax.swing.JLabel();
        forApePat = new javax.swing.JLabel();
        forApeMat = new javax.swing.JLabel();
        forTipoDocumento = new javax.swing.JLabel();
        marcarBtn = new javax.swing.JButton();
        areaLbl = new javax.swing.JLabel();
        forAreaLbl = new javax.swing.JLabel();
        tipMarcCmbBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal - Asesor");

        dniLbl.setText("ID:");
        forDniLbl.setText(this.asesor.obtenerUsuario());

        nombreLbl.setText("Nombre:");
        forNombreLbl.setText(this.asesor.obtenerNombre());

        apePatLbl.setText("Apellido Paterno:");
        forApePat.setText(this.asesor.obtenerApePat());

        apeMatLbl.setText("Apellido Materno:");
        forApeMat.setText(this.asesor.obtenerApeMat());

        tipoDocumento.setText("Tipo de documento:");
        forTipoDocumento.setText(this.asesor.obtenerTipoDocumento());
        
        areaLbl.setText("Area:");
        forAreaLbl.setText(this.asesor.obtenerArea());

        marcarBtn.setText("Marcar");

        this.agregarTipoMarcacion();
    
        //Eventos de JComboBox tipos de marcaciones
        tipMarcCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTipoMarcacion = obtenerIdTipoMarcacion();
            }
        });

        //Evento de JButton marcar
        marcarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String idEmp = asesor.obtenerUsuario();
                LocalDateTime ahora = LocalDateTime.now();
                marcar(idEmp, ahora, idTipoMarcacion);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(areaLbl)
                    .addComponent(apeMatLbl)
                    .addComponent(apePatLbl)
                    .addComponent(nombreLbl)
                    .addComponent(tipoDocumento)
                    .addComponent(dniLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forNombreLbl)
                    .addComponent(forDniLbl)
                    .addComponent(forApePat)
                    .addComponent(forTipoDocumento)
                    .addComponent(forAreaLbl)
                    .addComponent(forApeMat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tipMarcCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(marcarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLbl)
                    .addComponent(forDniLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(forNombreLbl)
                            .addComponent(nombreLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apePatLbl)
                            .addComponent(forApePat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(forApeMat)
                            .addComponent(apeMatLbl))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoDocumento)
                            .addComponent(forTipoDocumento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaLbl)
                            .addComponent(forAreaLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipMarcCmbBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(marcarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
