package com.grupo3.sistemamarcacion.vistas;

import com.grupo3.sistemamarcacion.controladores.InicioSesion;

public class MenuPrincipal extends javax.swing.JFrame
{
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel apeMatLbl;
    protected javax.swing.JLabel apePatLbl;
    protected javax.swing.JLabel dniLbl;
    protected javax.swing.JLabel forApeMat;
    protected javax.swing.JLabel forApePat;
    protected javax.swing.JLabel forDniLbl;
    protected javax.swing.JLabel forNombreLbl;
    protected javax.swing.JLabel forTipoDocumento;
    protected javax.swing.JButton marcarBtn;
    protected javax.swing.JLabel nombreLbl;
    protected javax.swing.JLabel relojLbl;
    protected javax.swing.JLabel tipoDocumentoLbl;
    // End of variables declaration//GEN-END:variables
    protected InicioSesion is;
    protected String idEmpleado;
    protected int idTipoEmpleado;

    public MenuPrincipal(String idEmpleado, int idTipoEmpleado)
    {
        this.idEmpleado = idEmpleado;
        this.idTipoEmpleado = idTipoEmpleado;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // </editor-fold>//GEN-END:initComponents
}
