package com.grupo3.sistemamarcacion.vistas;

import com.grupo3.sistemamarcacion.controladores.DatosEmpleado;
import com.grupo3.sistemamarcacion.empleado.Empleado;

public class Principal extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apeMatLbl;
    private javax.swing.JLabel apePatLbl;
    private javax.swing.JLabel dniLbl;
    private javax.swing.JLabel forApeMat;
    private javax.swing.JLabel forApePat;
    private javax.swing.JLabel forDniLbl;
    private javax.swing.JLabel forNombreLbl;
    private javax.swing.JLabel forTipoDocumento;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JLabel tipoDocumento;
    private String id;
    private Empleado empleado;
    // End of variables declaration//GEN-END:variables

    public Principal(String id)
    {
        this.id = id;
        this.empleado = new DatosEmpleado(this.id).obtenerEmpleado();
        this.initComponents();
        setLocationRelativeTo(null);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dniLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        apePatLbl = new javax.swing.JLabel();
        apeMatLbl = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JLabel();
        forDniLbl = new javax.swing.JLabel();
        forNombreLbl = new javax.swing.JLabel();
        forApePat = new javax.swing.JLabel();
        forApeMat = new javax.swing.JLabel();
        forTipoDocumento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dniLbl.setText("DNI:");

        nombreLbl.setText("Nombre:");

        apePatLbl.setText("Apellido Paterno:");

        apeMatLbl.setText("Apellido Materno:");

        tipoDocumento.setText("Tipo de documento:");

        forDniLbl.setText(this.empleado.obtenerUsuario());

        forNombreLbl.setText(this.empleado.obtenerNombre());

        forApePat.setText(this.empleado.obtenerApePat());

        forApeMat.setText(this.empleado.obtenerApeMat());

        forTipoDocumento.setText("forTipoDocumento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipoDocumento)
                        .addGap(60, 60, 60)
                        .addComponent(forTipoDocumento))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(apeMatLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forApeMat))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(forNombreLbl)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nombreLbl)
                                        .addComponent(dniLbl)
                                        .addComponent(apePatLbl))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(67, 67, 67)
                                            .addComponent(forApePat))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(forDniLbl)))))
                            .addGap(22, 22, 22))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLbl)
                    .addComponent(forDniLbl))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLbl)
                    .addComponent(forNombreLbl))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apePatLbl)
                    .addComponent(forApePat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apeMatLbl)
                    .addComponent(forApeMat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDocumento)
                    .addComponent(forTipoDocumento))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
