package com.grupo3.sistemamarcacion.tipomarcacion;

public enum TipoMarcacion
{
    MARCACIONENTRADAJORNADA,
    MARCACIONFINJORNADA,
    MARCACIONENTRADABANIO,
    MARCACIONFINBANIO,
    MARCACIONENTRADATOPICO,
    MARCACIONFINTOPICO,
    MARCACIONENTRADALACTANCIA,
    MARCACIONFINLACTANCIA
}
