package com.upn.colecciones.marcacion;

public enum TipoMarcacion
{
    MARCACIONENTRADAJORNADA,
    MARCACIONFINJORNADA,
    MARCACIONENTRADABANIO,
    MARCACIONFINBANIO,
    MARCACIONENTRADATOPICO,
    MARCACIONFINTOPICO,
    MARCACIONENTRADALACTANCIA,
    MARCACIONFINLACTANCIA
}
