DELIMITER $$
CREATE PROCEDURE CONFIRMAR_EXISTENCIA
    (
        IN ID VARCHAR(8), 
        IN PASS VARCHAR(255),
        OUT IDEMPLEADO VARCHAR(8),
        OUT TIPOEMPLEADO INT
    )
BEGIN

    SELECT
        A.ID,
        A.TIPOEMPLEADO 
        INTO IDEMPLEADO, TIPOEMPLEADO
    FROM
        EMPLEADOS AS A
    WHERE
        A.ID = ID AND
        A.CONTRASENIA = PASS;
    
END $$
DELIMITER ;
