DELIMITER $$
CREATE PROCEDURE MARCAR
	(
		IN FECHAHORA DATETIME,
        IN IDEMPLEADO VARCHAR(8),
		IN TIPOMARCACION INT
    )
BEGIN
	INSERT INTO MARCACION (FECHA, IDEMPLEADO, TIPOMARCACION)
    VALUES (FECHAHORA, IDEMPLEADO, TIPOMARCACION);
END $$
DELIMITER ;

