DELIMITER $$
CREATE PROCEDURE OBTENEREMPLEADO(IN IDEMPLEADO VARCHAR(8))
BEGIN

	SELECT 
		@idTipoEmpleado := A.TIPOEMPLEADO 
	FROM 
		EMPLEADOS AS A 
        WHERE A.ID = IDEMPLEADO;
	
	IF @idTipoEmpleado = 1 THEN
    
		SELECT
            A.ID AS "DNI",
            A.NOMBRE AS "NOMBRE",
            A.APEPAT AS "APELLIDO PATERNO",
            A.APEMAT AS "APELLIDO MATERNO",
            B.NOMBRE AS "TIPO DE EMPLEADO",
            C.NOMBRE AS "CARGO",
            E.NOMBRE AS "AREA DE TRABAJO"
        FROM 
            EMPLEADOS AS A 
        INNER JOIN TIPODOCUMENTO AS B
            ON (A.TIPODOCUMENTO = B.ID)
        INNER JOIN TIPOEMPLEADO AS C
            ON (A.TIPOEMPLEADO = C.ID)
        INNER JOIN ASESORES AS D
            ON (A.ID = D.ID)
        INNER JOIN AREAS AS E
            ON (D.AREATRABAJO = E.ID)
        WHERE A.ID = IDEMPLEADO;

    ELSEIF @idTipoEmpleado = 2 THEN

        SELECT
            A.ID AS "DNI",
            A.NOMBRE AS "NOMBRE",
            A.APEPAT AS "APELLIDO PATERNO",
            A.APEMAT AS "APELLIDO MATERNO",
            B.NOMBRE AS "TIPO DE EMPLEADO",
            C.NOMBRE AS "CARGO",
            E.NOMBRE AS "CAMPAÑA A CARGO"
        FROM 
            EMPLEADOS AS A 
        INNER JOIN TIPODOCUMENTO AS B
            ON (A.TIPODOCUMENTO = B.ID)
        INNER JOIN TIPOEMPLEADO AS C
            ON (A.TIPOEMPLEADO = C.ID)
        INNER JOIN COORDINADORES AS D
            ON (A.ID = D.ID)
        INNER JOIN CAMPANIA AS E
            ON (D.CAMPANIACOORDINADA = E.ID)
        WHERE A.ID = IDEMPLEADO;
    
    ELSEIF @idTipoEmpleado = 3 THEN

        SELECT
            A.ID AS "DNI",
            A.NOMBRE AS "NOMBRE",
            A.APEPAT AS "APELLIDO PATERNO",
            A.APEMAT AS "APELLIDO MATERNO",
            B.NOMBRE AS "TIPO DE EMPLEADO",
            C.NOMBRE AS "CARGO",
            E.NOMBRE AS "AREA A CARGO"
        FROM 
            EMPLEADOS AS A 
        INNER JOIN TIPODOCUMENTO AS B
            ON (A.TIPODOCUMENTO = B.ID)
        INNER JOIN TIPOEMPLEADO AS C
            ON (A.TIPOEMPLEADO = C.ID)
        INNER JOIN SUPERVISORES AS D
            ON (A.ID = D.ID)
        INNER JOIN AREAS AS E
            ON (D.AREASUPERVISADA = E.ID)
        WHERE A.ID = IDEMPLEADO;

    ELSE 

        SELECT
            A.ID AS "DNI",
            A.NOMBRE AS "NOMBRE",
            A.APEPAT AS "APELLIDO PATERNO",
            A.APEMAT AS "APELLIDO MATERNO",
            B.NOMBRE AS "TIPO DE EMPLEADO",
            C.NOMBRE AS "CARGO"
        FROM 
            EMPLEADOS AS A 
        INNER JOIN TIPODOCUMENTO AS B
            ON (A.TIPODOCUMENTO = B.ID)
        INNER JOIN TIPOEMPLEADO AS C
            ON (A.TIPOEMPLEADO = C.ID)
        WHERE A.ID = IDEMPLEADO;
    END IF;
END $$
DELIMITER ;


-- CONSULTA ASESORES
SELECT
    A.ID AS "DNI",
    A.NOMBRE AS "NOMBRE EMPLEADO",
    A.APEPAT AS "APELLIDO PATERNO",
    A.APEMAT AS "APELLIDO MATERNO",
    A.TIPODOCUMENTO AS "TIPO DOCUMENTO",
    B.AREATRABAJO AS "ID AREA",
    C.NOMBRE AS "NOMBRE AREA",
    C.TIPO AS "TIPO AREA",
    D.ID AS "ID CAMPANIA",
    D.NOMBRE AS "NOMBRE CAMPAÑA"
FROM 
    EMPLEADOS AS A
INNER JOIN 
    ASESORES AS B
ON A.ID = B.ID
INNER JOIN
    AREAS AS C
ON B.AREATRABAJO = C.ID
INNER JOIN 
    CAMPANIA AS D
ON C.CAMPANIA = D.ID
WHERE
    A.ID = "74576066";

-- CONSULTA COORDINADORES
SELECT
    A.ID AS "DNI",
    A.NOMBRE AS "NOMBRE EMPLEADO",
    A.APEPAT AS "APELLIDO PATERNO",
    A.APEMAT AS "APELLIDO MATERNO",
    A.TIPODOCUMENTO AS "TIPO DOCUMENTO",
    B.CAMPANIACOORDINADA AS "ID CAMPANIA",
    C.NOMBRE AS "NOMBRE CAMPANIA"
FROM 
    EMPLEADOS AS A
INNER JOIN 
    COORDINADORES AS B
ON A.ID = B.ID 
INNER JOIN
    CAMPANIA AS C
ON B.CAMPANIACOORDINADA = C.ID
WHERE
    A.ID = "12334578";

-- CONSULTA SUPERVISORES
SELECT
    A.ID AS "DNI",
    A.NOMBRE AS "NOMBRE EMPLEADO",
    A.APEPAT AS "APELLIDO PATERNO",
    A.APEMAT AS "APELLIDO MATERNO",
    A.TIPODOCUMENTO AS "TIPO DOCUMENTO",
    B.AREASUPERVISADA  AS "ID AREA",
    C.NOMBRE AS "NOMBRE AREA",
    C.TIPO AS "TIPO AREA",
    C.CAMPANIA AS "ID CAMPANIA",
    D.NOMBRE AS "NOMBRE CAMPANIA"
FROM 
    EMPLEADOS AS A
INNER JOIN 
    SUPERVISORES AS B
ON A.ID = B.ID 
INNER JOIN
    AREAS AS C
ON B.AREASUPERVISADA = C.ID
INNER JOIN 
    CAMPANIA AS D
ON C.CAMPANIA = D.ID
WHERE
    A.ID = "75328598";

-- CONSULTA RRHH
SELECT
    A.ID AS "DNI",
    A.NOMBRE AS "NOMBRE EMPLEADO",
    A.APEPAT AS "APELLIDO PATERNO",
    A.APEMAT AS "APELLIDO MATERNO",
    A.TIPODOCUMENTO AS "TIPO DOCUMENTO"
FROM 
    EMPLEADOS AS A
INNER JOIN 
    RRHH AS B
ON A.ID = B.ID 
WHERE
    A.ID = "87654321";
