DELIMITER $$
CREATE PROCEDURE OBTENER_SUPERVISOR
    (
        IN ID VARCHAR(8),
        OUT ID_EMPLEADO VARCHAR(8),
        OUT NOMBRE VARCHAR(40),
        OUT APE_PAT VARCHAR(50),
        OUT APE_MAT VARCHAR(50),
        OUT TIPO_DOCUMENTO INT, -- 6
        OUT ID_AREA INT,
        OUT NOMBRE_AREA VARCHAR(50),
        OUT TIPO_AREA INT,
        OUT ID_CAMPANIA INT,
        OUT NOMBRE_CAMPANIA VARCHAR(50) 
    )
BEGIN
    -- CONSULTA SUPERVISORES
    SELECT
        A.ID AS "DNI",
        A.NOMBRE AS "NOMBRE EMPLEADO",
        A.APEPAT AS "APELLIDO PATERNO",
        A.APEMAT AS "APELLIDO MATERNO",
        A.TIPODOCUMENTO AS "TIPO DOCUMENTO",
        B.AREASUPERVISADA  AS "ID AREA",
        C.NOMBRE AS "NOMBRE AREA",
        C.TIPO AS "TIPO AREA",
        C.CAMPANIA AS "ID CAMPANIA",
        D.NOMBRE AS "NOMBRE CAMPANIA"
        INTO ID_EMPLEADO, NOMBRE, APE_PAT, APE_MAT, TIPO_DOCUMENTO, ID_AREA, 
            NOMBRE_AREA, TIPO_AREA, ID_CAMPANIA, NOMBRE_CAMPANIA
    FROM 
        EMPLEADOS AS A
    INNER JOIN 
        SUPERVISORES AS B
    ON A.ID = B.ID 
    INNER JOIN
        AREAS AS C
    ON B.AREASUPERVISADA = C.ID
    INNER JOIN 
        CAMPANIA AS D
    ON C.CAMPANIA = D.ID
    WHERE
        A.ID = ID;
END $$
DELIMITER ;
