DELIMITER $$
CREATE PROCEDURE OBTENER_COORDINADOR
    (
        IN ID VARCHAR(8),
        OUT ID_EMPLEADO VARCHAR(8),
        OUT NOMBRE VARCHAR(40),
        OUT APE_PAT VARCHAR(50),
        OUT APE_MAT VARCHAR(50),
        OUT TIPO_DOCUMENTO INT,
        OUT ID_CAMPANIA INT,
        OUT NOMBRE_CAMPANIA VARCHAR(50) 
    )
BEGIN
    -- CONSULTA COORDINADORES
    SELECT
        A.ID AS "ID",
        A.NOMBRE AS "NOMBRE EMPLEADO",
        A.APEPAT AS "APELLIDO PATERNO",
        A.APEMAT AS "APELLIDO MATERNO",
        A.TIPODOCUMENTO AS "TIPO DOCUMENTO",
        B.CAMPANIACOORDINADA AS "ID CAMPANIA",
        C.NOMBRE AS "NOMBRE CAMPANIA"
        INTO ID_EMPLEADO, NOMBRE, APE_PAT, APE_MAT, TIPO_DOCUMENTO, ID_CAMPANIA, 
            NOMBRE_CAMPANIA
    FROM 
        EMPLEADOS AS A
    INNER JOIN 
        COORDINADORES AS B
    ON A.ID = B.ID 
    INNER JOIN
        CAMPANIA AS C
    ON B.CAMPANIACOORDINADA = C.ID
    WHERE
        A.ID = ID;
END $$
DELIMITER ;
